import type { Student, Class } from './definitions';

export const classes: Class[] = [
  { id: 'class1', name: '1 UPM' },
  { id: 'class2', name: '1 UKM' },
  { id: 'class3', name: '2 USM' },
];

export const students: Student[] = [
  {
    id: '1',
    name: 'Liam Johnson',
    username: 'liamj',
    avatar: 'https://picsum.photos/seed/1/100/100',
    progress: 90,
    timePlayed: 240,
    experimentScore: 90,
    activityScore: 80,
    classId: 'class1',
  },
  {
    id: '2',
    name: 'Olivia Smith',
    username: 'olivias',
    avatar: 'https://picsum.photos/seed/2/100/100',
    progress: 50,
    timePlayed: 120,
    experimentScore: 50,
    activityScore: 40,
    classId: 'class1',
  },
  {
    id: '3',
    name: 'Noah Williams',
    username: 'noahw',
    avatar: 'https://picsum.photos/seed/3/100/100',
    progress: 95,
    timePlayed: 320,
    experimentScore: 95,
    activityScore: 89,
    classId: 'class2',
  },
  {
    id: '4',
    name: 'Emma Brown',
    username: 'emmab',
    avatar: 'https://picsum.photos/seed/4/100/100',
    progress: 20,
    timePlayed: 30,
    experimentScore: 20,
    activityScore: 10,
    classId: 'class2',
  },
  {
    id: '5',
    name: 'Oliver Jones',
    username: 'oliverj',
    avatar: 'https://picsum.photos/seed/5/100/100',
    progress: 80,
    timePlayed: 180,
    experimentScore: 80,
    activityScore: 72,
    classId: 'class3',
  },
  {
    id: '6',
    name: 'Ava Garcia',
    username: 'avag',
    avatar: 'https://picsum.photos/seed/6/100/100',
    progress: 70,
    timePlayed: 200,
    experimentScore: 70,
    activityScore: 66,
    classId: 'class1',
  },
  {
    id: '7',
    name: 'Elijah Miller',
    username: 'elijahm',
    avatar: 'https://picsum.photos/seed/7/100/100',
    progress: 25,
    timePlayed: 60,
    experimentScore: 25,
    activityScore: 19,
    classId: 'class2',
  },
  {
    id: '8',
    name: 'Charlotte Davis',
    username: 'charlotted',
    avatar: 'https://picsum.photos/seed/8/100/100',
    progress: 100,
    timePlayed: 450,
    experimentScore: 100,
    activityScore: 100,
    classId: 'class3',
  },
  {
    id: '9',
    name: 'James Rodriguez',
    username: 'jamesr',
    avatar: 'https://picsum.photos/seed/9/100/100',
    progress: 10,
    timePlayed: 15,
    experimentScore: 10,
    activityScore: 0,
    classId: 'class1',
  },
  {
    id: '10',
    name: 'Sophia Martinez',
    username: 'sophiam',
    avatar: 'https://picsum.photos/seed/10/100/100',
    progress: 60,
    timePlayed: 150,
    experimentScore: 60,
    activityScore: 50,
    classId: 'class3',
  },
  {
    id: '11',
    name: 'Benjamin Hernandez',
    username: 'benjaminh',
    avatar: 'https://picsum.photos/seed/11/100/100',
    progress: 92,
    timePlayed: 280,
    experimentScore: 92,
    activityScore: 84,
    classId: 'class2',
  },
  {
    id: '12',
    name: 'Isabella Lopez',
    username: 'isabellal',
    avatar: 'https://picsum.photos/seed/12/100/100',
    progress: 35,
    timePlayed: 90,
    experimentScore: 35,
    activityScore: 25,
    classId: 'class3',
  },
];
